embeddings:
  glove: '/home/cps8/data/glove.6B.50d_normalized.txt'

paths:
  annotations: '/data/dl_lecture_data/TrainVal/annotations'
  train_images: '/data/dl_lecture_data/TrainVal/train2014'
  validation_images: '/data/dl_lecture_data/TrainVal/val2014'

image_dimensions: [224, 224, 3]

word_embedding_size: 50

max_caption_length: 25
