embeddings:
  glove: '/Users/nils/Desktop/test/glove/glove.6B.50d_normalized.txt'

paths:
  annotations: '/Users/nils/Desktop/test/dl_env/TrainVal/annotations'
  train_images: '/Users/nils/Desktop/test/dl_env/TrainVal/train2014'
  val_images: '/Users/nils/Desktop/test/dl_env/TrainVal/val2014'
  test_metadata: '/Users/nils/Desktop/test/dl_env/test'
  test_images: '/Users/nils/Desktop/test/dl_env/test'
  logs: '/home/cps8/logs'
  models: '/home/cps8/models'

image_dimensions: [224, 224, 3]

word_embedding_size: 50

max_caption_length: 25